### ISSUE TITLE
Crontab path to Python3.8

### ISSUE THREAD

**Issue by tlitke5** [alphabet5/guacamole-compose#15]
The path to Python3.8 is incorrect. 

-bash: /usr/local/bin/python3.8: No such file or directory

**Comment by alphabet5** [comment]
When installing python manually - ie Centos 7, following these instructions, it's installed to /usr/local/bin/python3.8.

```bash
sudo yum -y update
sudo yum -y groupinstall "Development Tools"
sudo yum -y install openssl-devel bzip2-devel libffi-devel
sudo yum -y install gcc
sudo yum -y install wget
wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
tar xvd Python-3.8.5.tgz
cd Python-3.8*
./configure --enable-optimizations
sudo make altinstall
```

If python3.8 is installed with dnf - ie Centos 8, it's installed to /usr/bin/python3.8

I'll add notes to the documentation.
